server:
   port: 8761
   
   
eureka:
   instance:
     hostname: localhost
     statusPageUrlPath: ${management.contextPath}/info
     healthCheckUrlPath: ${management.contextPath}/health
   client:
       registerWithEureka: false
       fetchRegistry: false
       server: 
          waitTimeInMsWhenSyncEmpty: 0
       serviceUrl:
         defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
         defaultZone: http://server.port/eureka/, http://server.port/eureka/
                              #localhost:8761/eureka/
                              #localhost:8762/eureka/

spring:
   application:
      name: eurekaserver



  
